// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestAPI.Models;

#nullable disable

namespace RestAPI.Migrations
{
    [DbContext(typeof(RestAPIDBContext))]
    [Migration("20220925132252_WFM init")]
    partial class WFMinit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RestAPI.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("varchar");

                    b.Property<decimal?>("Experience")
                        .HasPrecision(5)
                        .HasColumnType("decimal(5,0)");

                    b.Property<string>("LockStatus")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Manager")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("WfmManager")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("RestAPI.Models.SkillMap", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Skillid")
                        .HasColumnType("int");

                    b.Property<int>("SkillsSkillid")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Skillid");

                    b.HasIndex("SkillsSkillid");

                    b.ToTable("SkillMaps", (string)null);
                });

            modelBuilder.Entity("RestAPI.Models.Skills", b =>
                {
                    b.Property<int>("Skillid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Skillid"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Skillid");

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("RestAPI.Models.SkillMap", b =>
                {
                    b.HasOne("RestAPI.Models.Employee", "Employees")
                        .WithMany("SkillMaps")
                        .HasForeignKey("Skillid")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RestAPI.Models.Skills", "Skills")
                        .WithMany("SkillMaps")
                        .HasForeignKey("SkillsSkillid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employees");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("RestAPI.Models.Employee", b =>
                {
                    b.Navigation("SkillMaps");
                });

            modelBuilder.Entity("RestAPI.Models.Skills", b =>
                {
                    b.Navigation("SkillMaps");
                });
#pragma warning restore 612, 618
        }
    }
}
